### ISSUE TITLE
使用说明

### ISSUE THREAD

**Issue by vvVenom** [bytedance/scene#11]
可以加一个Scene的生命周期列举图吗

**Comment by vvVenom** [comment]
@qii 共享元素除了用在打开新的scene之外能用在其他地方上吗，比如使用在一个系统的activity上，且共享元素貌似不能自定义duration？

**Comment by qii** [comment]
1.Activity 打开 Scene 吗，有个 ActivityToSceneSharedElementSceneTransitionExecutor 主要用来兼容迁移的时候，从原来的 UI 做动画过渡到新的 Scene
2.我擦，还真是。。。。找个时间补

**Comment by vvVenom** [comment]
> 1.Activity 打开 Scene 吗，有个 ActivityToSceneSharedElementSceneTransitionExecutor 主要用来兼容迁移的时候，从原来的 UI 做动画过渡到新的 Scene

不是的，表达方式有点问题，应该是在一个scene中，我有一个布局想通过点击按钮来将这个布局转换成另一个布局，但不需要打开新的scene...？

**Comment by vvVenom** [comment]
@qii 共享元素在 RecyclerView 中应该怎么使用，要为每一个 item 包一层 Scene 吗

**Comment by qii** [comment]
> @qii 共享元素在 RecyclerView 中应该怎么使用，要为每一个 item 包一层 Scene 吗

不用，recyclerview item 还是照旧，只要前后2个页面的View中有同名 (transitionname相同）View就会计算前后的属性做动画。

改天我加个demo吧

**Comment by qii** [comment]
> 可以加一个Scene的生命周期列举图吗

https://github.com/bytedance/scene/wiki/Lifecycle
