### ISSUE TITLE
Kotlin直接取用控件id

### ISSUE THREAD

**Issue by Iridescentangle** [bytedance/scene#12]
![image](https://user-images.githubusercontent.com/33859295/70512928-8ed51000-1b6b-11ea-974d-fcd656e6c9b7.png)
Kotlin支持的直接调用控件id不可用,因为只对Activity、Fragment或Dialog适用..
想请教一下有什么好的解决办法嘛

**Comment by Ccixyj** [comment]
kotlin可以对view直接取id的。scene持有view对象

**Comment by qii** [comment]
我觉得难啊，那个是 android plugin 提供的吧，难道我得自己写个 apt 。。。

**Comment by qii** [comment]
。。。。话说我是没怎么用过 kotlin 直接根据id拿到View，我看那些教程，貌似可以直接对任意的view进行这样操作，我是看的这个文章 https://antonioleiva.com/kotlin-android-extensions/

**Comment by Iridescentangle** [comment]
> 我觉得难啊，那个是 android plugin 提供的吧，难道我得自己写个 apt 。。。
额 不懂这个，不过我今天看了，这个extension是针对Dialog、Activity、Fragment的，其他的的话除了要导入布局，还要导入布局.view.*
例如:
import kotlinx.android.synthetic.main.activity_main.*
import kotlinx.android.synthetic.main.activity_main.view.*
这样可以用view.xxx唤出来了

**Comment by Iridescentangle** [comment]
> kotlin可以对view直接取id的。scene持有view对象
恩 不过还是要多一步，导入view.*，然后在调用时候使用view.xxx调用

**Comment by gtf35** [comment]
接上面的，不止要导入 view.*，还要在 app 级别的 build.gradle 里加入如下内容，启用实验性特征
android {
    ...
    androidExtensions {
        experimental = true
    }
    ....
}

官方文档如下：https://kotlinlang.org/docs/tutorials/android-plugin.html#enabling-experimental-features
