### ISSUE TITLE
请问在结合ViewModel使用时候,应该在onDestroy还是在onDestroyView移除监听呢

### ISSUE THREAD

**Issue by Iridescentangle** [bytedance/scene#16]
![image](https://user-images.githubusercontent.com/33859295/71061061-1f31d700-21a2-11ea-865d-07367d168b33.png)
如图,onDestroy提示已弃用,所以改用onDestroyView中移除,但会报出Coroutines任务取消的异常,请问这个是否需要处理呢...
![image](https://user-images.githubusercontent.com/33859295/71061201-7d5eba00-21a2-11ea-848a-7f5e1d3417b8.png)

kotlinx.coroutines.JobCancellationException: Job was cancelled; job=SupervisorJobImpl{Cancelling}@5c2f9ea

**Comment by qii** [comment]
你的这个 viewModel 变量是怎么赋值的，贴来看看

**Comment by Iridescentangle** [comment]
> 你的这个 viewModel 变量是怎么赋值的，贴来看看
![image](https://user-images.githubusercontent.com/33859295/71063129-142d7580-21a7-11ea-8042-3de5a3e66a05.png)

![image](https://user-images.githubusercontent.com/33859295/71063073-f52ee380-21a6-11ea-8970-1c5b01897d36.png)
由于ViewModelProviders.of()入参只支持Activity或者Fragment,所以这里是通过Factory来获取provider的

**Comment by qii** [comment]
你这个 viewmodel 只是给 scene 自己用的吗？还是通讯用的？
前者的话 SceneViewModelProviders.of(Scene)，后者的话我没搞懂为啥你用lifecycle.addObserver(viewModel)

**Comment by Iridescentangle** [comment]
> 你这个 viewmodel 只是给 scene 自己用的吗？还是通讯用的？
> 前者的话 SceneViewModelProviders.of(Scene)，后者的话我没搞懂为啥你用lifecycle.addObserver(viewModel)
是Scene自己用的.懂了,用SceneViewModelProviders来获取,非常感谢!
