### ISSUE TITLE
请教一下关于三方WebView在inflate的时候出现的强转错误

### ISSUE THREAD

**Issue by Iridescentangle** [bytedance/scene#19]
![image](https://user-images.githubusercontent.com/33859295/71322205-0c9c0280-2500-11ea-8d74-68b6ed0cd3ce.png)
如图所示,使用了基于腾讯X5WebView的YCWebView 链接[https://github.com/yangchong211/YCWebView](url)
但在inflate过程中会报错，Scene cannot cast to Activity...
求解，有什么好办法...

**Comment by qii** [comment]
```java
abstract class ActivityContextGroupScene extends UserVisibleHintGroupScene {
    @Override
    protected final LayoutInflater onGetLayoutInflater() {
        return requireActivity().getLayoutInflater();
    }
}

abstract class ActivityContextScene extends Scene {
    @Override
    protected final LayoutInflater onGetLayoutInflater() {
        return requireActivity().getLayoutInflater();
    }
}
```

**Comment by Iridescentangle** [comment]
> ```java
> abstract class ActivityContextScene extends Scene {
>     @Override
>     protected final LayoutInflater onGetLayoutInflater() {
>         return requireActivity().getLayoutInflater();
>     }
> }
> ```

好的，非常感谢!!!
