### ISSUE TITLE
关于拦截Pop动作的问题

### ISSUE THREAD

**Issue by Iridescentangle** [bytedance/scene#20]
项目结构是主页BottomNavigationView配合几个Scene切换,所以按照Demo中的拦截Pop页面加入了
![image](https://user-images.githubusercontent.com/33859295/71333618-9df98c00-2575-11ea-9f9d-b30a16514b0c.png)

但是在这个页面同级的其他Scene中也会响应该返回事件

**Comment by qii** [comment]
可以在回调里面判断当前Scene是不是可见
```java
if (getLifecycle().getCurrentState().isAtLeast(Lifecycle.State.STARTED)) {

                    } else {
                        return false;
                    }
```

最初设计的时候，是一定要可见才能拦截，后来改坏了……就一直没修……因为觉得补一段if else就没事了……

**Comment by Iridescentangle** [comment]
> ```java
> if (getLifecycle().getCurrentState().isAtLeast(Lifecycle.State.STARTED)) {
> 
>                     } else {
>                         return false;
>                     }
> ```

好的
