### ISSUE TITLE
请教一个关于PushResultCallback的问题

### ISSUE THREAD

**Issue by Iridescentangle** [bytedance/scene#21]
项目是模块化开发的,之前在传递一个实体类的时候很顺利,但是现在传递Boolean和String,在pushResultCallback中可以收到回调,但result始终为空.
![image](https://user-images.githubusercontent.com/33859295/71668797-43e29d00-2da5-11ea-8579-74aaf4a5c704.png)

我仔细地查找了和有效代码不同的地方,只有这一点,就是回传的实体类是实现了Serializable的,而之后两次使用传递的则是String和Boolean
求解~~~

**Comment by qii** [comment]
https://github.com/bytedance/scene/blob/b7299ff5fe34f933bffa9170c35ea361ec5a00c9/demo/src/main/java/com/bytedance/scenedemo/navigation/forresult/SceneResultScene_1.kt#L37  demo里面传的就是String，跑起来是正常的
