### ISSUE TITLE
addOnBackPressedListener 共用引起的问题

### ISSUE THREAD

**Issue by wflian** [bytedance/scene#24]
在首页写得了监听addOnBackPressedListener，结果全部页面返回键全部走这个方法，全部需要快速按两次才可以

**Comment by wflian** [comment]
虽然这个问题很容易就解决了，但是这样的话返回键监听就不是每个页面自己管理自己的，默写情况下确实很不好，比如：某个页面  要弹出对话框提示 是否放弃编辑

**Comment by qii** [comment]
https://github.com/bytedance/scene/issues/20 

嗯，打算之后改改

**Comment by qii** [comment]
https://github.com/bytedance/scene/commit/3dc15e1f2e5ce0acc662c65613475ee386341a24   

版本更新的话得过阵子……

**Comment by qii** [comment]
v1.0.4 发布 fix https://github.com/bytedance/scene/releases/tag/v1.0.4
