### ISSUE TITLE
结合类似Glide这类自己绑定生命周期的如何使用？

### ISSUE THREAD

**Issue by wflian** [bytedance/scene#26]
比如：Glide这种带有什么周期感知的，自动暂停等，但是只支持view、activity、fragment这些，那么要如何配合Scene使用呢?如何传入activity的话，那么生命周期就跟随activity，也无关scene ，那就没有意义了

**Comment by qii** [comment]
如果 glide 能支持外部设置 lifecycle 就好做了，我翻了翻 glide 的 issues，好像有类似的 pull request，但是官方没要，被关了。。。
要不你先照着 https://github.com/MkhytarMkhoian/ConductorGlide 试试

**Comment by qii** [comment]
https://github.com/bytedance/scene/wiki/Glide

**Comment by qii** [comment]
你试试 wiki 里面的写法 😓
