### ISSUE TITLE
这个库的想法很好啊！这么多BUG，怎么这么久都没更新呢？

### ISSUE THREAD

**Issue by wflian** [bytedance/scene#30]

**Comment by qii** [comment]
1. 工作很忙事情多
2. 修的commit还得先在公司内的版本上验证，但是现在还有另外一个比较重要的commit在适配 https://github.com/bytedance/scene/commit/13156681c1ff292e01fc0aa8498ce7880a71ea5d

**Comment by Ccixyj** [comment]
这个库不错的。项目已经用了。很好。更新也很勤快了。你比对一下conductor😂
