### ISSUE TITLE
能否支持ARouter组件化

### ISSUE THREAD

**Issue by Android-wangmeng** [bytedance/scene#32]
目前组件化是趋势，请问楼主能否支持下，谢谢！

**Comment by qii** [comment]
哭了……真的很忙

**Comment by freeyob** [comment]
我想来支持这个feature

**Comment by qii** [comment]
> 我想来支持这个 feature

你是打算在 arouter 上扩展，还是自己写套新的 router

**Comment by qii** [comment]
https://github.com/bytedance/scene/tree/scene_router  这里有未完工的 Scene Router 代码

**Comment by freeyob** [comment]
> https://github.com/bytedance/scene/tree/scene_router 这里有未完工的 Scene Router 代码

好的。我这边先看一下。

**Comment by zombiu** [comment]
> > https://github.com/bytedance/scene/tree/scene_router 这里有未完工的 Scene Router 代码
> 
> 好的。我这边先看一下。

大佬给力，就等你的router了！

**Comment by qii** [comment]
发了个 router 0.0.1 版本，使用可以参照 https://github.com/bytedance/scene/tree/scene-router-samples，后续补文档

**Comment by qii** [comment]
https://github.com/bytedance/scene/wiki/Router
