### ISSUE TITLE
通过setupWithFragment创建的scene如何获取activity绑定的的NavigationScene

### ISSUE THREAD

**Issue by Ccixyj** [bytedance/scene#37]
因为是改造的旧项目。所以会有fragment和activity的两种迁移方式.
```
MainActivity--  NavigationSceneUtility.setupWithActivity -- EmptyholderScene
   |
  viewpager -- |
           Homefragment  -- GroupSceneUtility.setupWithFragment -- HomeScene 
           other fragments

```
我在HomeScene 中点击并想要从MainActivity的NavigationScene push 一个scene, 请问怎么才能从HomeScene 获取MainActivity绑定的NavigationScene？

**Comment by Ccixyj** [comment]
现在使用的方式为activity实现一个可以获取navigationScene的接口。子scene获取activity后强转为改接口并获取。感觉这个方式不是很好。

**Comment by qii** [comment]
。。。。感觉没啥好办法
