### ISSUE TITLE
Scene Event/Router

### ISSUE THREAD

**Issue by Harlber** [bytedance/scene#4]
- 首先表示感谢，从这个项目中学到了很多
 - 目前正在调研是否可以接入公司项目（首页也是单Activity，多Fragment，bugly线上反映的Fragment问题不少），不知道后续是否会支持类似Scene-Event之类的组件来支持Scene间通信，尤其是在Group的场景下
 - 组件化的项目中，router功能不知道会不会被支持，如果有这个功能，相信会有非常多的人想去尝试的！

**Comment by qii** [comment]
Event：曾经想做，写着写着，发现EventBus这种机制，比起RxJava的PublishSubject<Class>/官方的LiveData没有优势，后者好追查多了（当然LiveData其实是个BehaviorSubject，做Event还得魔改下），于是就没提交代码进仓库了。

Router：努努力这个月尽快弄完，其实写是写的差不多了，但刚出来的话bug应该会挺多的吧（大概吧）……

**Comment by qii** [comment]
Scene的组件通讯机制依赖的是Scope，我得补充文档和demo

**Comment by OnClickListener2048** [comment]
很佩服楼主的能力，一年内独自完成这么大的工程量，感觉是把activity fragment的所有交互方式完整的搬运到view中来了&nbsp; 虽然还有一些适配的问题但仍然很赞




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"qiibeta"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月4日(星期一) 下午4:19
收件人:&nbsp;"bytedance/scene"<scene@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [bytedance/scene] Scene Event/Router (#4)




Event：曾经想做，写着写着，发现EventBus这种机制，比起RxJava的PublishSubject/官方的LiveData没有优势，后者好追查多了（当然LiveData其实是个BehaviorSubject，做Event还得魔改下），于是就没提交代码进仓库了。
 
Router：努努力这个月尽快弄完，其实写是写的差不多了，但刚出来的话bug应该会挺多的吧（大概吧）……

**Comment by Harlber** [comment]
> Scene的组件通讯机制依赖的是Scope，我得补充文档和demo

有这个就很赞了，不然很可能各种野事件满天飞，
BTW，最期待的还是路由功能，再往后面就希望暴露些Trace接口，做做性能优化（提需求果然爽😊）

**Comment by qii** [comment]
发了个 router 0.0.1 版本，使用可以参照 https://github.com/bytedance/scene/tree/scene-router-samples 后续补文档

**Comment by qii** [comment]
https://github.com/bytedance/scene/wiki/Router
