### ISSUE TITLE
仿照BottomNavigationViewSample写的一个底部切换页面，初始化显示的目标scene错误！

### ISSUE THREAD

**Issue by zombiu** [bytedance/scene#40]
{2131362082=TabChildScene(pos=1), 2131362083=TabChildScene(pos=0), 2131362085=TabChildScene(pos=3), 2131362086=TabChildScene(pos=4), 2131362087=TabChildScene(pos=2)}
debug发现内部scene排序异常。

**Comment by qii** [comment]
GroupSceneUIUtility.setupWithBottomNavigationView 的 SparseArrayCompat 你改 LinkedHashMap 吧，赋值出来一份改改，我后续fix这个问题

**Comment by zombiu** [comment]
大佬加油，努力更新！
