### ISSUE TITLE
scene长时间在后台，页面恢复出现问题！

### ISSUE THREAD

**Issue by zombiu** [bytedance/scene#41]
[https://github.com/zombiu/-/blob/master/S00430-15504030.png](url)
机型 魅族 note8
scene的demo放在后台两天没管，然后再重新打开，界面恢复之后就优点问题，除了最上面的三个按钮可以点击，其它都不能点击！

**Comment by Pluckypan** [comment]
> [https://github.com/zombiu/-/blob/master/S00430-15504030.png](url)
> 机型 魅族 note8
> scene的demo放在后台两天没管，然后再重新打开，界面恢复之后就优点问题，除了最上面的三个按钮可以点击，其它都不能点击！

scene:are you kidding me?

**Comment by qii** [comment]
看着是销毁重建导致的页面重叠了，因为 demo 的 SceneActivity 其实是通过 androidx fragment 作为转发，假如 androidx 的 fragment 销毁重建出 bug，是有可能出这个 bug 的，在公司内部的使用里面其实是手动用 lifecycledispatcher/lifecyclemanager 分发的，一直没遇到这种 bug，考虑到 androidx 更新了那么多版本，这个问题我先关闭了，假如后续还有出现，我再来看
