### ISSUE TITLE
SceneDelegate和GroupSceneDelegate的abandon()是否需要用户处理

### ISSUE THREAD

**Issue by Ccixyj** [bytedance/scene#42]
如题，abandon的调用时机是什么?用户要手动处理吗

**Comment by qii** [comment]
有些情况下，需要把所有的 Scene 都销毁然后重新创建，就需要先 abandon，然后重新 setup

**Comment by Ccixyj** [comment]
> 有些情况下，需要把所有的 Scene 都销毁然后重新创建，就需要先 abandon，然后重新 setup

好的，谢谢回答
