### ISSUE TITLE
Why not update to androidx

### ISSUE THREAD

**Issue by mokhtarabadi** [bytedance/scene#47]
I see androidx branch, but why not applied that to master, I using androidx branch and don't see any bugs until now

**Comment by qii** [comment]
some app codebase still use support library in bytedance

**Comment by mokhtarabadi** [comment]
I using this library in two complex android project, what is the future of scene?
Any update or active developing?

**Comment by qii** [comment]
The current state is mainly maintenance, fix bugs

**Comment by qii** [comment]
androidx branch will merge to master branch in January 2021

**Comment by qii** [comment]
https://github.com/bytedance/scene/releases/tag/v1.1.0

done
