### ISSUE TITLE
 SceneInstanceUtility可见性问题

### ISSUE THREAD

**Issue by Ccixyj** [bytedance/scene#5]
根据文档 `Migration to Scene`，用SceneInstanceUtility类在不同的包下显示
`SceneInstanceUtility can only be called from within the same library group (groupId=com.bytedance.scene)`。

**Comment by qii** [comment]
哪里的文档，首页的readme吗，貌似我没写用到SceneInstanceUtility，我印象里面wiki里面也没写直接用SceneInstanceUtility吧。。。（或者我眼花了？

**Comment by Ccixyj** [comment]
中文readme里面
