### ISSUE TITLE
Why not using material components?

### ISSUE THREAD

**Issue by mokhtarabadi** [bytedance/scene#51]
I see you written xml templates in scene-ui by using linear layout and a custom root layout based on it

Why not using material library components in androidx branch like coordinator layout to easy access status bar and navigation bar
Or others like appbar, material toolbar, linear layout compat and also for bottom navigation and scene content can use coordinator behaviors

I currently used edited xml&java to fill my needs, but the codes not follow project codebase so I can't make PR

And one thing more, merge master to androidx if possible

**Comment by qii** [comment]
I just wanted to make a simple version (Scene + Toolbar + Content) before, the StatusBarView and NavigationView need to consume Inset before content view, the logic is similar to com.android.internal.policy.DecorView#updateColorViews

master is already merged into the androidx branch
