### ISSUE TITLE
Deep linking?

### ISSUE THREAD

**Issue by mokhtarabadi** [bytedance/scene#52]
Is there deep linking available?
When it's will ready and how can I use that?

I cooding android side of a social network and I need handle deep link to open profiles, media and other items in the app by link

**Comment by qii** [comment]
tutorial/deeplinks branch

just support basic usage

https://github.com/bytedance/scene/blob/tutorial/deeplinks/app/src/main/java/com/bytedance/scene/deeplinks/MainActivity.kt
