### ISSUE TITLE
Demo singleTask 用法和singleTop 一样啊，不会清除要启动的sense 栈上面的sense

### ISSUE THREAD

**Issue by sevennight1989** [bytedance/scene#53]

**Comment by qii** [comment]
我都有点后悔加了个 singletask，本身 Activity 的 launchmode 各种混乱，就不该模拟这个……

**Comment by qii** [comment]
其实 LaunchMode 后来整个重做了，跟 Activity 对齐了，我估计这个过一阵子会同步

**Comment by qii** [comment]
https://github.com/bytedance/scene/commit/701fbb4b86599c3482f236a701fdc4833c8b6df8
