### ISSUE TITLE
scene跨进程打开另外一个页面 可以解决白屏问题吗？

### ISSUE THREAD

**Issue by hebao5201314** [bytedance/scene#54]

**Comment by qii** [comment]
白屏问题是一直白屏，还是开始几百毫米或几秒的白屏？

**Comment by hebao5201314** [comment]
> 白屏问题是一直白屏，还是开始几百毫米或几秒的白屏？

启动过程中几百毫秒 或 几秒的白屏，不是一直白屏。

**Comment by qii** [comment]
你这个另外的页面 Activity 内部也是用的 Scene 对吗？你直接用的 SceneActivity 还是单独自己绑定的，贴下加载 Scene 的代码我看看

**Comment by hebao5201314** [comment]
> 你这个另外的页面 Activity 内部也是用的 Scene 对吗？你直接用的 SceneActivity 还是单独自己绑定的，贴下加载 Scene 的代码我看看
我还没有接入Scene，我看readme.mk可以解决启动白屏问题，所以想咨询下scene是否能够解决跨进程启动页面时遇到白屏问题，如果能够解决考虑接入scene

**Comment by hebao5201314** [comment]
> 你这个另外的页面 Activity 内部也是用的 Scene 对吗？你直接用的 SceneActivity 还是单独自己绑定的，贴下加载 Scene 的代码我看看

我还没有接入Scene，我看readme.mk可以解决启动白屏问题，所以想咨询下scene是否能够解决跨进程启动页面时遇到白屏问题，如果能够解决考虑接入scene

**Comment by qii** [comment]
但是这个解决的是同个进程里面开关 Activity 的黑屏，解决不了你跨进程的需求
