### ISSUE TITLE
出现空指针

### ISSUE THREAD

**Issue by Ccixyj** [bytedance/scene#55]
NavigationScene 的push系列方法参数pushOptions都是可空的。但是NavigationSceneManager的pushOptions是非空的。
如果NavigationScene 传空的pushOptions就空指针了
`    public void push(@NonNull Class<? extends Scene> clazz, @Nullable Bundle argument, @Nullable PushOptions pushOptions) {`
`    public void push(@NonNull Scene scene, @Nullable PushOptions pushOptions) {`
应用直接调用的这两个方法。但是pushOptions应用中式可空的

**Comment by qii** [comment]
。。。。是的，内部版本已经修了，还没同步到开源的版本，还需要一阵子，在这个之前还有个重要的修改还没上线，把 scene 拆分出了一个 scene-navigation 库

**Comment by qii** [comment]
https://github.com/bytedance/scene/commit/c7a07782efbdc4111ac4a5eb33e3ac8db210920e

1.3.1 fix
