### ISSUE TITLE
无法拉取新版本更新依赖的问题。

### ISSUE THREAD

**Issue by bozaixing** [bytedance/scene#59]
v1.2.0版本scene-ui、scene-shared-element-animation、scene-ktx这三个库无法拉取更新。

**Comment by qii** [comment]
是因为jcenter关门了，你用这个
```
allprojects {
	repositories {
		...
		maven { url 'https://jitpack.io' }
	}
}
```

**Comment by bozaixing** [comment]
我配置了maven { url 'https://jitpack.io' }这个远程地址的，但是依旧提示拉去失败，提示信息如下：
Failed to resolve: com.bytedance.scene:scene-ktx:v1.2.0
Show in Project Structure dialog
Affected Modules: app

Failed to resolve: com.bytedance.scene:scene:v1.2.0
Show in Project Structure dialog
Affected Modules: app

Failed to resolve: com.bytedance.scene:scene-ui:v1.2.0
Show in Project Structure dialog
Affected Modules: app

Failed to resolve: com.bytedance.scene:scene-shared-element-animation:v1.2.0
Show in Project Structure dialog
Affected Modules: app

**Comment by qii** [comment]
我今天找时间看下

**Comment by bozaixing** [comment]
嗯嗯，麻烦你了，谢谢了。

**Comment by qii** [comment]
忘了，jitpack 的名字不太一样，是这样的。。。。

dependencies {
        implementation 'com.github.bytedance.scene:scene:v1.2.0'
        implementation 'com.github.bytedance.scene:scene-ui:v1.2.0'
        implementation 'com.github.bytedance.scene:scene-shared-element-animation:v1.2.0'
        implementation 'com.github.bytedance.scene:scene-ktx:v1.2.0'
}

**Comment by bozaixing** [comment]
更改你提供的配置后，核心Scene包拉取正常，但是其余三个依旧无法拉取成功，提示如下：
Failed to resolve: com.github.bytedance.scene:scene-shared-element-animation:v1.2.0
Show in Project Structure dialog
Affected Modules: app

Failed to resolve: com.github.bytedance.scene:scene-ui:v1.2.0
Show in Project Structure dialog
Affected Modules: app

Failed to resolve: com.github.bytedance.scene:scene-ktx:v1.2.0
Show in Project Structure dialog
Affected Modules: app

**Comment by qii** [comment]
得用下划线 囧

```
    implementation 'com.github.bytedance.scene:scene:v1.2.0'
    implementation 'com.github.bytedance.scene:scene_ui:v1.2.0'
    implementation 'com.github.bytedance.scene:scene_navigation:v1.2.0'
    implementation 'com.github.bytedance.scene:scene_shared_element_animation:v1.2.0'
    implementation 'com.github.bytedance.scene:scene_ktx:v1.2.0'
```

**Comment by bozaixing** [comment]
谢谢了，已经拉取成功了。
