### ISSUE TITLE
BottomNavigationViewScene的底部menu点击事件回调能否传出来？

### ISSUE THREAD

**Issue by zhangbohui10** [bytedance/scene#67]
我看在BottomNavigationViewScene中是由GroupSceneUIUtility.setupWithBottomNavigationView方法内部设置了setOnNavigationItemSelectedListener，而该listener的点击事件并没有对外公开，如果有场景需要监听该点击，该如何监听？

**Comment by qii** [comment]
等我有空了看看，囧

**Comment by Iridescentangle** [comment]
我记得我之前是拷了一份出来自己改的
