### ISSUE TITLE
多层嵌套的问题

### ISSUE THREAD

**Issue by ail36413** [bytedance/scene#68]
AScene 
  ---BScene
       -----B1Scene <->B2Scene <-> B3Scene

这种嵌套的情况可以实现吗？ A页面里面有个占比50%的B页面，B页面里面的b1、b2、b3在做push pop,不影响外面A界面

**Comment by ail36413** [comment]
使用NavigationSceneOptions去嵌套的话。背景不能透明？

**Comment by qii** [comment]
NavigationSceneOptions 是有选项，默认是用 windowBackground 去填充背景色的，你可以关掉
