### ISSUE TITLE
大佬，最低SDK太高了

### ISSUE THREAD

**Issue by fanqingwen** [bytedance/scene#71]
首先感谢大佬的很好用的库，我看最新的最低版本已经更新到21了，作为这样的基础框架，应该保持最低吧，我拉了源码改了最低版本在API 17的设备上跑了跑没啥问题，主要我们的用户还存在大量的Android4.2 的车机设备，再次感谢

**Comment by qii** [comment]
我主要是考虑到现在微信抖音都 21 了，现在车机上面的 android 版本这么低的啊

**Comment by fanqingwen** [comment]
是的，几年前的车机还很多5.1一下的，比如21年的长安，吉利啥的很多Android4.2的系统，最近几年的车机设备在新能源这么卷的情况下才快速发展的，这东西生命周期很长，大部分人车机不坏是不会更换的基本上跟车生命周期一样，不像手机更新这么快，像高德地图的车机版，QQ音乐车机版等还是保持的低版本，我用这个库也是因为为了优化性能，很多车机性能很拉，内存也低，希望大佬考虑下，感谢。

**Comment by qii** [comment]
.....这个，你要不就拿最新源码魔改个minisdk版本用着吧，反正这个框架最新版本相当的稳定，没啥大问题，抖音&TikTok 这么大的体量都在跑
