### ISSUE TITLE
MainActivity使用delegate 点击穿透的问题

### ISSUE THREAD

**Issue by LailaiMaster** [bytedance/scene#8]
你好，我参考西瓜视频首页迁移方案，出现点击穿透的问题。
另一个是，可以更新下文档和demo吧，感觉demo中用的都是过时的方法，比如setupWithActivity，我看现在不都是用build了么。

**Comment by qii** [comment]
你暂时可以在根View设置clickable，我没想好这个库在push新Scene是不是应该直接帮用户做了这个事情。 第二个没吧，demo里应该没有用老的deprecated的setupWithActivity吧

**Comment by vvVenom** [comment]
> 你暂时可以在根View设置clickable，我没想好这个库在push新Scene是不是应该直接帮用户做了这个事情。 第二个没吧，demo里应该没有用老的deprecated的setupWithActivity吧

内部的 SceneActivity 貌似就是使用的弃用的
![image](https://user-images.githubusercontent.com/58068445/70540780-cf02b580-1ba0-11ea-9fca-daabd9431ac3.png)

**Comment by qii** [comment]
额，抽空改改

**Comment by qii** [comment]
> > 你暂时可以在根View设置clickable，我没想好这个库在push新Scene是不是应该直接帮用户做了这个事情。 第二个没吧，demo里应该没有用老的deprecated的setupWithActivity吧
> 
> 内部的 SceneActivity 貌似就是使用的弃用的
> ![image](https://user-images.githubusercontent.com/58068445/70540780-cf02b580-1ba0-11ea-9fca-daabd9431ac3.png)

1.0.3 已修复
